spring:
 datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hisdb
    username: root
    password: root
 jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
        
server:
  port: 9091
---
spring:
  application:
    name: AR_API
  boot:
    admin:
          client:
            url: http://localhost:8080/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'

 
